spring: 
    profiles: 
        active: 
          - dev
---
spring: 
  profiles: dev #开发环境
  application: 
    name: cloud-config-studysai-dev
---
spring: 
  profiles: test #测试环境
  application: 
    name: cloud-config-studysai-test
#utf-8保存s                